/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NewRouteImport } from './routes/new'
import { Route as ArchivedRouteImport } from './routes/archived'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as TagsTagRouteImport } from './routes/tags/$tag'
import { Route as NotesNoteIdRouteImport } from './routes/notes/$noteId'
import { Route as ApiWebhooksRouteImport } from './routes/api/webhooks'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivedRoute = ArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRoute = ApiWebhooksRouteImport.update({
  id: '/api/webhooks',
  path: '/api/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/new': typeof NewRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/webhooks': typeof ApiWebhooksRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/tags/$tag': typeof TagsTagRoute
  '/notes': typeof NotesIndexRoute
  '/tags': typeof TagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/new': typeof NewRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/webhooks': typeof ApiWebhooksRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/tags/$tag': typeof TagsTagRoute
  '/notes': typeof NotesIndexRoute
  '/tags': typeof TagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/new': typeof NewRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/webhooks': typeof ApiWebhooksRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/tags/$tag': typeof TagsTagRoute
  '/notes/': typeof NotesIndexRoute
  '/tags/': typeof TagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archived'
    | '/new'
    | '/search'
    | '/settings'
    | '/api/webhooks'
    | '/notes/$noteId'
    | '/tags/$tag'
    | '/notes'
    | '/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archived'
    | '/new'
    | '/search'
    | '/settings'
    | '/api/webhooks'
    | '/notes/$noteId'
    | '/tags/$tag'
    | '/notes'
    | '/tags'
  id:
    | '__root__'
    | '/'
    | '/archived'
    | '/new'
    | '/search'
    | '/settings'
    | '/api/webhooks'
    | '/notes/$noteId'
    | '/tags/$tag'
    | '/notes/'
    | '/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivedRoute: typeof ArchivedRoute
  NewRoute: typeof NewRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ApiWebhooksRoute: typeof ApiWebhooksRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  TagsTagRoute: typeof TagsTagRoute
  NotesIndexRoute: typeof NotesIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archived': {
      id: '/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof ArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks': {
      id: '/api/webhooks'
      path: '/api/webhooks'
      fullPath: '/api/webhooks'
      preLoaderRoute: typeof ApiWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivedRoute: ArchivedRoute,
  NewRoute: NewRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ApiWebhooksRoute: ApiWebhooksRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  TagsTagRoute: TagsTagRoute,
  NotesIndexRoute: NotesIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
